- .travis.yml
- fenicsadapter/__init__.py
- fenicsadapter/fenicsadapter.py
- setup.py
- tests/test_fenicsadapter.py
- tests/test_write_read.py
Enable the adapter to be used for FSI with FEniCS as 2D structure solver. 
List of new features:
- Introduce treatment of vector valued data and functions in FEniCS. Displacements and Forces are vector valued functions and have to be treated correspondingly.
- Buffer the RBF interpolation in the CustomExpression class for runtime improvement in FSI simulations
- Use PointSource for quantities that are mapped conservatively and are applied to mesh nodes (used for Forces)
- `read_block_vector_data` and `read_block_scalar_data` are wrapped into `read_block_data` that differentiates between the two cases (scalar/vector) and calls the respective preCICE function
> Support FSI with fenics as a Structure Solver

- .travis.yml
This adds triggering of  FEniCS-FEniCS system test, that was added here  https://github.com/precice/systemtests/pull/79 and updated to docker-compose here https://github.com/precice/systemtests/pull/86.
> Add systemtests triggering

- fenicsadapter/fenicsadapter.py
- tests/test_write_read.py
Adding interface mesh edge definitions necessary to enable `nearest-projection` mapping in preCICE. This added functionality is tested using [this tutorial case](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics). From the working of `nearest-neighbor` and `nearest-projection` we understand that `nearest-projection` will estimate the exact solution of the 2D Poissons equation if the problem setup is devised in a way that the analytical solution is linear in the direction of flux of the Neumann boundary condition. More on this formulation can be found in [this document](https://fenicsproject.org/pub/tutorial/pdf/fenics-tutorial-vol1.pdf) on page no. 16 Section 2.1.3
The results of this tutorial problem are shown below:
> Mapping nearestprojection

- fenicsadapter/checkpointing.py
- fenicsadapter/solverstate.py
* introduce explicit `get_copy()`
* discard initialization of `SolverState` with `None` in `checkpointing.py`
> Fix checkpointing and solverstate copy for tuples

- .travis.yml
- fenicsadapter/fenicsadapter.py
- setup.py
- tests/test_fenicsadapter.py
- tests/test_write_read.py
This PR refactors the adapter to use the [new python bindings](https://github.com/precice/precice/tree/develop/src/precice/bindings/python_future). This PR is intended to be merge consecutively with https://github.com/precice/precice/pull/547 to ensure that error handling for all entities is done only once, either in the adapter or in the bindings.
> Refactoring adapter to use new python bindings

- fenicsadapter/fenicsadapter.py
For the actions I propose to not import them with a `from` statement, but only `import precice` and then access them via `precice.`.
> Remove unnecessary import

- fenicsprecice/adapter_core.py
- fenicsprecice/config.py
- fenicsprecice/fenicsprecice.py
- tests/test_fenicsprecice.py
This PR overhauls the initialization to make it more versatile. The new initialization function can be used to initialize uni-directional coupling cases. The proposed initialization also addresses: https://github.com/precice/fenics-adapter/issues/89 and makes the adapter initialization more robust.
Closes https://github.com/precice/fenics-adapter/issues/89
To-Do before merging this:
> Overhaul Initialization

- fenicsprecice/expression_core.py
Tried to run a test with 4+6 ranks, where some ranks resulted in using the `EmptyExpression` and crashed due to this invalid function call.
> Fix wrong function call

- setup.py
Setting FEniCS as install requirement may break the installation (see #103). We therefore check whether FEniCS is installed and abort, if this is not the case.
Closes #103.
@fsimonis @IshaanDesai What do you think about this approach?
> Remove FEniCS as requirement

- .github/workflows/check-links.yml
- CHANGELOG.md
- README.md
- docs/ReleaseGuide.md
I reformatted our md files according to the pipeline introduced in 9ddb497. I accidentally pushed 9ddb497 to develop, but I don't think we have to revert it, if we merge die PR quickly.
I also removed the disclaimer from the README.md, because I think it is not necessary.
@MakisH "stealing" from https://github.com/precice/openfoam-adapter/pull/170 worked very nicely btw.
> Fix formatting according to new pipeline

- .github/workflows/build-and-test.yml
- CHANGELOG.md
- setup.py
This PR introduces CI to test for the issue observed in #126
> Test python3 setup.py sdist

- setup.py
This warns users with python ~~3.6.8~~ 3.6.9. See https://github.com/precice/fenics-adapter/pull/61 for more details.
This issue was also discussed on discourse. Refer to the video posted under https://precice.discourse.group/t/fenics-adapter-installation/652/5.
> Adds a warning, if python 3.6.9 is used

- fenicsprecice/adapter_core.py
- fenicsprecice/fenicsprecice.py
This PR refactors the functions used to filter FEniCS DoFs for relevant vertex information for parallel computations. This refactoring was done as part of implementing 3D capability and was also tested on the LRZ Linux Cluster and found to reduce initialization time by a significant factor.
> Optimizing DoF filtering while extracting vertex data from FEniCS

- fenicsprecice/adapter_core.py
- fenicsprecice/fenicsprecice.py
This PR adds 3D case handling capability to the adapter. Currently only 3D FSI serial cases are tested. The testing is done with the help of the `elastic-tube-3d` case: https://github.com/precice/tutorials/pull/222. Closes https://github.com/precice/fenics-adapter/issues/1
> Add 3D case support capability for serial FSI cases

- fenicsprecice/adapter_core.py
- fenicsprecice/fenicsprecice.py
- tests/unit/test_adapter_core.py
Added configuration of connectivity data for volume coupling: triangles from the coupling domain are added to the preCICE mesh.
It (seems to) works in serial & parallel, however the parallel version has "holes", as triangles made of owned+unowned vertices are discared:
This is however consistent with the current implementation, which does the same in surface coupling with edges.
Questions:
- Currently this is always done. Should it be a parameter, or should we rely on preCICE to ignore useless connectivity? THere are no checks for edges and I went for consistency first...
- There is an assertion that the mesh is made of triangles. Not ideal, but I'm open to suggestions for alternatives. How would it work with quads or in  3D ?
- Some parts of the code aren't very pythonic, I'm open to …
> Adding connectivity data for volume coupling

- CITATION.cff
- docs/ReleaseGuide.md
* Use `preferred-citation` to point to the FEniCS-preCICE paper
* Provide citation information about software on top level.
* Open for discussion: Might be extended with other/future contributors that did not author the paper. Important: We need a proper and simple policy here. See also https://github.com/precice/fenics-adapter/graphs/contributors
* Add a DOI? We could point to the preCICE distribution, but this is actually a superset of FEniCS-preCICE and the policy w.r.t. authorship is also independent. I would rather keep things separate and not provide a DOI. If we really want a DOI, we can still release on zenodo. This looks to me like the go-to-solution suggested by the CFF developers: https://citation-file-format.github.io/
> Update `CITATION.cff` to use `preferred-citation`

- .github/workflows/build-docker.yml
- tools/releasing/packaging/docker/Dockerfile
Should fix #160 
Here a similar idea to the python-bindings applies: 
I Made the Workflow a bit more usable via the manual dispatch and also split up `latest` and `develop` tags accordingly. 
Additionally the Dockerfile is more in line with the current approach to Dockerfiles used in the Systemtestsv2
> Build `latest` docker container from master not `develop` branch

- .github/workflows/build-and-test.yml
- tools/testing/docker/Dockerfile
The image `quay.io/fenicsproject/stable:current` triggers the following error in our tests: 
```
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/fenicsproject/stable:current to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
I, therefore, created my own image based on a fenics installation with `apt`.
> Use `benjaminrodenberg/fenics` for CI stage "Build and Test"

- CHANGELOG.md
- tests/unit/test_checkpointing.py
These tests are written in context of Pull Request https://github.com/precice/fenics-adapter/pull/172
Since the core functionality of the checkpointing is implemented in the SolverState class, the tests are actually testing only this class. 
This commit consists of three different tests:
1. Write checkpoint & directly load it (just for the sake of completeness)
2. Write checkpoint of a function, then modify the dof vector of the dolfin function by directly accessing it via `vector()`. After that, load the checkpoint.
3. Write checkpoint of a function, then modify the this dolfin function via `assign()`. After that, load the checkpoint.
> Tests checking implementation of checkpointing/SolverState

- setup.py
I removed the checks for the following reasons:
1. FEniCS check turns out problematic in #181 
2. If we follow the recommended installation procedure `pip install .` the warnings are not shown. The warnings only appear for the deprecated `python3 setup.py install`
We can check for the python version (and potentially also FEniCS) when moving to `pyproject.toml` in a better way (see #179).
> Remove checks for FEniCS and python3

- CHANGELOG.md
- setup.py
This PR closes https://github.com/precice/fenics-adapter/issues/180.
`setup_requires=['mpi4py<4']` is necessary as this requirement is needed for the imported FEniCS below.
> Modify `setup.py` to avoid crash due to version 4.0.0 of `mpi4py` during installation

- README.md
Closes https://github.com/precice/fenics-adapter/issues/164
> Clarify installation procedure

- .github/workflows/build-and-test.yml
- CHANGELOG.md
- CITATION.cff
- README.md
- fenicsprecice/solverstate.py
- setup.py
- tests/integration/test_fenicsprecice.py
- tests/unit/test_checkpointing.py
- tools/testing/docker/Dockerfile
This release comes with some minor modifications to simplify the installation process and an important bugfix when subcycling is used (see #172).
> Release v2.2.0
